### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by markuznw** [pavlovtech/WebReaper#1]
Hello and thanks for your work. Took me a while to figure out how to use it but now it works and it's quite fast
Just have a question: is there a way to automatically skip duplicates? Maybe keep a list of already seen urls or what?

Thank you <3

**Comment by pavlovtech** [comment]
Hello! You are welcome and thank you for trying out my library.

As for your question, sure, there is a way to skip duplicates. In fact, duplicates are skipped by default, but with the use of in memory list, so it is not persisted on the disk or database (see InMemoryCrawledLinkTracker).

If you want to skip duplicates when you run the crawler multiple times, you could use  the already implemented  RedisCrawledLinkTracker that uses Redis (see the example in the project DistributedScraperWorkerService):

scraper = new Scraper()
...// all other config methods
.WithLinkTracker(new RedisCrawledLinkTracker(redisConnectionString))

You can actually keep a list of already seen urls with your own implementation of the ICrawledLinkTracker interface if Redis doesn't fit your needs.
