### ISSUE TITLE
[Recommendation] Separate the HTML parser framework from the core library

### ISSUE THREAD

**Issue by iyilm4z** [pavlovtech/WebReaper#13]
I always follow a pattern: Create separate projects for major dependencies. 

For a crawler, we generally use HtmlAgilityPack and AngleSharp as HTML parsers. In the beginning, we use them rarely but later on, we use them in many places and they become a major dependency. I see that your core library Exoscan depends on HtmlAgilityPack. I recommend creating a separate project named Exoscan.HtmlAgilityPack and put the concrete implementation in this project. 

I usually prefer AngleSharp so, if you were having Exoscan.HtmlAgilityPack or Exoscan.AngleSharp package options, I would prefer your Exoscan.AngleSharp package. Because I already use AngleSharp in my current project for other parsing businesses. 

I think you chose the current design for keeping things simple. I respect it for sure. My opinion is just a recommendation for flexibility.

**Comment by iyilm4z** [comment]
Also the same for Puppeteer. I prefer Playwright.

**Comment by pavlovtech** [comment]
@iyilm4z thank you, appreciate the feedback! Creating a separate project for 3rd party dependencies indeed makes sense. However, any referenced projects must be published as separate NuGet packages as well, which is not practical if your package is not going to work without it and it would be installed anyways. 

For the most part, 3rd party dependencies in Exoscan are abstracted away via interfaces, so it is possible to swap out the implementation, e.g. IBrowserPageLoader with PuppeteerPageLoader implementation.

I'm planning to move some optional external dependencies to separate packages such as Redis, Mongo DB, Azure Service Bus, etc. 

But I see that I have a tight coupling with AngleSharp and creating Exoscan.AngleSharp makes sense as well, thank you for pointing that out!
