### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by serdar-sahin** [pavlovtech/WebReaper#19]
First of all, thanks for the project.
When I apply the code "var engine = await new ScraperEngineBuilder() " as in the example, it gives "System.NullReferenceException"  error.
What could be the problem?

**Comment by serdar-sahin** [comment]
There is a problem with the package downloaded via nuget. It works when compiled from source code.
For your information. Thanks.

**Comment by pavlovtech** [comment]
Hi @serdar-sahin @bogdan799

Thank you for your feedback! The NuGet package is updated with a fix for this issue.
